#!/bin/sh

# battery
status="$(cat /sys/class/power_supply/BAT1/status)"
capacity="$(cat /sys/class/power_supply/BAT1/capacity)"
case "$status" in
  Discharging) printf "󰣐  $capacity%% ";;
  Full) printf "󰣐 = ";;
  *) printf "󰻹  $capacity%%+ ";;
esac

# amixer
status="$(amixer get Master | awk -F'[]%[]' 'END{ print $7 }')"
volume="$(amixer get Master | awk -F'[]%[]' 'END{ print $2 }')"
case "$status" in
  on) printf "  $volume%% " ;;
  off) printf " - " ;;
esac
